[nuyhhyun] 자동차 경주 게임(코틀린 스터디)
croffle-lover/kotlin-racingcar pull request #4
Opened 2023-12-29 07:20 UTC by nuyhhyun

2023-12-29 11:21 UTC, croffle-lover requested changes
고생 많으셨습니다! 😆
몇 가지 피드백 남겨드렸으니 반영 또는 질문에 대한 답을 댓글로 남겨주시고 다시 리뷰요청 해주세요!

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/utils/Messages.kt
> +}
코틀린은 다음과 같이 최상위 프로퍼티 최상위 함수를 정의할 수 있습니다.

```kotlin
// Message.kt
const val CAR_NAMES_PLEASE = "경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분)."
const val MORE_THAN_ONE_CAR = "자동차는 두 대 이상 입력해야 합니다."
const val ANY_NAME_NEEDED = "자동차 이름은 반드시 입력해야 합니다."
const val NOT_LONGER_THAN_5 = "자동차 이름은 5자를 초과할 수 없습니다."
const val TRY_COUNTS_PLEASE = "시도할 횟수는 몇 회인가요?"
const val SHOULD_BE_NUMBER = "시도 횟수는 숫자여야 합니다."
const val MOVE_RESULT = "실행 결과"
const val FINAL_WINNER = "최종 우승자: "
```

하지만 지금은 저 상수들이 사용되는 곳에 각각 위치하는 것이 응집도를 올릴 수 있을 것 같습니다!
소프트웨어 설계에 있어서 응집도는 높게 결합도는 낮게하는게 권장됩니다!
지금은 무슨 말일지 모르시겠다면 검색하면서 뉘앙스를 익히시면 좋을 것 같아요!

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/ui/InputView.kt
> +import racingcar.utils.Validations as VALIDATION
이런식으로 import를 활용하여 이름을 바꾼 이유는 무엇인가요?
만약 없다면 굳이 명시하지 않아도 괜찮을 것 같아요!

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/ui/InputView.kt
> +}
InputView의 경우 여러개의 인스턴스가 만들어질 필요가 없어서 싱글톤 객체로 만들고 싶으셨던 것 같은데,
kotlin은 `object`라는 키워드로 쉽게 클래스를 싱글톤으로 만들 수 있습니다!
굳이 클래스 안에 `companion object`로 구현 하실 필요가 없습니다!

참고: [object](https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview)

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/ui/InputView.kt
> +        }
`return carNamesInput!!.trim().split(',')`

!!을 사용하면 자바의 고질적인 문제인 NPE(null point exception) 문제를 해결하려고 마련해놓은 코틀린의 null을 관리하는 여러가지 장치들을 사용하지 않고 그대로 사용하는거나 다름없습니다!

물론 null 일 수가 없게끔 코딩을 해놔서 !!을 사용해도 프로그램이 잘 돌아갈 수 있지만, 개발자가 실수를 할 수 도 있으니 되도록이면 안쓰는게 권장됩니다!

코틀린 인 액션 책에서는 `!!` 키워드는 마치 컴파일러에게 소리치듯 하게끔 보이게 만든거라고 합니다.
컴파일러를 놀라게 하지 맙시다!

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +data class Car(val name: String, var position: Int)
지금의 `Car` 객체는 var인 position을 외부에서 맘대로 조절할 수 있습니다!

어떻게 하면 외부에서 직접적으로 position을 수정하지 않고
우리의 게임 규칙 대로 한칸씩만 올라가게 할 수 있을까요?

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +data class Car(val name: String, var position: Int)
아 그리고 Car 객체는 따로 파일로 분리를 해놓는게 더 보기 좋을 것 같습니다!

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +        }
주석을 무작정 사용하지 말라는 말은 못합니다만! 
주석이 없어도 코드를 이해함에 문제가 안된다면 과감하게 없애는게 좋을 것 같습니다!

2023-12-29 11:21 UTC, croffle-lover commented on src/test/kotlin/ui/InputViewTest.kt
> +class InputViewTest {
요구사항에 보시면 UI에 대한 단위 테스트는 제외한다 라고 나와있습니다!
그래도 고생하셨어요!

2023-12-29 11:21 UTC, croffle-lover commented on README.md
> +초간단 자동차 경주 게임을 구현한다.
기능 목록 상세하게 잘 적어주셨네요! 이모지도 귀엽구요!

기능 목록은 프로그램의 일종의 명세가 됩니다.

다른 개발자가 보고 '아 이 레이싱 게임에는 이런 기능들이 있구나' 라고 프로그램을 이해하는 속도가 빨라지기에

협업이 거의 필수인 개발자로서 문서화도 중요한 스킬입니다.

또한 

### **기능목록을 상세히 적으면 그것이 곧 테스트 해야할 목록과도 같습니다.**

기능 목록 만으로는 어떻게 프로그램이 구현되는지 상세한 과정을 알지 못합니다.

테스트 코드는 다릅니다. 잘 짜여진 테스트 코드들은 프로그램이 구동되는 원리를 알기 쉽습니다!

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/Application.kt
> +import racingcar.domain.GameManager as GAME
이것도 마찬가지로 `GameManager` 여도 상관 없을 것 같아요!

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +class GameManager {
지금 이 `GameManager`는 뷰의 일도, 모델의 일도, 컨트롤러의 일도하는 전지전능한 객체입니다!

![](https://refactoring.guru/images/refactoring/content/smells/large-class-01.png?id=acac82f25cc90aaa413c2daefebf0e4b)

이런 클래스는 어떤게 문제가 될까요?

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +class GameManager {
또 분리한다면 어떻게 할 수 있을까요?

2023-12-29 11:21 UTC, croffle-lover commented on src/main/kotlin/racingcar/ui/InputView.kt
> +        }
[코틀린 공식문서 - null safety](https://kotlinlang.org/docs/null-safety.html)

2024-01-02 12:32 UTC, nuyhhyun commented on src/main/kotlin/racingcar/ui/InputView.kt
> +import racingcar.utils.Validations as VALIDATION
전에 다른 분 코드를 보고 프로퍼티를 대문자로 명명해둬서 저렇게 하면 통일성을 줄 수 있나보다 싶어서 따라 써보던 부분이었습니다! 다들 저렇게 하는 줄 알았는데 없어도 된다면 그게 더 편할 것도 같습니다ㅎㅎ 적용해보겠습니다 감사합니다!

2024-01-02 13:35 UTC, nuyhhyun commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +data class Car(val name: String, var position: Int)
> 지금의 `Car` 객체는 var인 position을 외부에서 맘대로 조절할 수 있습니다!
> 
> 어떻게 하면 외부에서 직접적으로 position을 수정하지 않고 우리의 게임 규칙 대로 한칸씩만 올라가게 할 수 있을까요?

칸 수가 증가해야 할 때 Car 객체 안에서 바꿀 수 있도록 Car 객체 안에 함수를 만들어 그 함수를 호출하는 방법이 생각나는데, 그렇게 다시 코드 짜보고 리뷰 요청드리겠습니다!

2024-01-02 14:13 UTC, nuyhhyun commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +class GameManager {
> 지금 이 `GameManager`는 뷰의 일도, 모델의 일도, 컨트롤러의 일도하는 전지전능한 객체입니다!
> 
> ![](https://camo.githubusercontent.com/b7986094dbf1d66ec918daaf85873d8ad69c2f4e3538a14627a5956733fe8c43/68747470733a2f2f7265666163746f72696e672e677572752f696d616765732f7265666163746f72696e672f636f6e74656e742f736d656c6c732f6c617267652d636c6173732d30312e706e673f69643d6163616338326632356363393061616134313363326461656665626630653462)
> 
> 이런 클래스는 어떤게 문제가 될까요?

앞서 말씀해주셨던 것과 반대로 결합도가 강하고 응집도가 약한 상태인 게 문제가 될 것 같습니다. GameManager라는 객체가 무슨 일을 하는 지 명확히 알기 힘들고, 협업으로 여러 명이 각각 뷰, 모델, 컨트롤러에 대해 수정을 할 때 곤란한 경우도 생길 수 있을 것 같습니다.

2024-01-02 14:20 UTC, nuyhhyun commented on src/test/kotlin/ui/InputViewTest.kt
> +class InputViewTest {
아 안그래도 고민이었는데 프리코스 때 예외적인 입력이 들어왔을 때를 고려하는 테스트 코드 얘기가 많았던 기억이 있어서 포함시키게 됐던 것 같습니다! 밑에 얘기해주신 내용 참고하여 테스트 구현해보겠습니다!

2024-01-02 14:27 UTC, nuyhhyun commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +class GameManager {
> 또 분리한다면 어떻게 할 수 있을까요?

소프트웨어 디자인 패턴을 활용해서 분리하는 것이 적당해 보입니다! 이래서 다들 MVC 패턴을 많이 얘기했나 봅니다.. MVC 패턴으로 분리한다면, Model에 자동차와 시도 횟수 데이터, View에 출력, Controller에 게임 동작 기능으로 나눌 수 있을 것 같습니다. 이렇게 재구성하여 코드 리팩토링 해보고 다시 리뷰 요청 드리겠습니다! 감사합니다!

2024-01-04 13:15 UTC, croffle-lover requested changes
고생하셨습니다 현님!
다음부터는 리뷰를 반영한 커밋도 분리해서 올려주세요!

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/Car.kt
> +    }
지금의 경우는 `position`을 public으로 풀어둔거랑 같습니다!
setter를 update라는 이름으로 바꾼 메서드입니다!
이 레이싱 게임을 할 때 한 번에 position을 1보다 크게 이동시키는 케이스가 있을까요?~
좀 더 제한시켜도 좋을 것 같아요!
그래도 제 의도대로 함수를 통해 객체에게 값 변경을 요청하게 잘하셨습니다! 😃

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/Car.kt
> +    }
```kotlin
var setterVisibility: String = "abc"
    private set
```

위처럼 외부엔 노출 시키면서 외부에선 변경을 못하게 막을 수 있어요!

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/Car.kt
> +    }
코틀린의 프로퍼티는 필드가 아닌 프로퍼티라고 불리는 이유가 있습니다.
프로퍼티는 데이터인 필드와, 필드를 getter와 setter를 포함합니다.
코틀린에서 프로퍼티는 이미 게터가 선언되어 있으므로 따로 이렇게 만들어 주시지 않아도 됩니다!
다른 클래스에도 많이 보이는데 같이 수정해주세요!

참고: [Kotlin - Properties](https://kotlinlang.org/docs/properties.html)

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/view/InputView.kt
> +const val TRY_COUNTS_PLEASE = "시도할 횟수는 몇 회인가요?"
파일별로 나눠놓으셨군요! 좋습니다.
하지만 여전히 다른 파일에서도 이 상수들을 참조할 수가 있습니다.
접근 제한자를 지정하여 다른 파일에서 접근하지 못하게 해볼까요?

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +        }
해당 함수에서 사용하는 10과 4가 무엇을 의미하는지 이 코드를 처음 보는 개발자가 알아보기 쉬우려면 어떻게 해야할까요? 

힌트: ㅅㅅㅎ

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/Validations.kt
> +class Validations {
Validation이 필요한 곳에서 각각 가지고 있으면 좋을 것 같아요!
자동차 이름이 5글자를 넘는지 이런건 어느 클래스에서 검증해줘야할까요?

지금은 실생활로 비유하면 자동차모양 레고, 로봇 모양 레고의 각 상자에 설명서를 넣는 것이 아닌 
따로 설명서들만 모아서 파일철로 관리하는 것과 같습니다!

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/Validations.kt
> +class Validations {
또한 이렇게 런타임 떄 객체의 인스턴스화가 필요없는 클래스는 싱글톤으로 관리, 즉 `ojbect`의 사용을 권장드립니다!

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/view/OutputView.kt
> +    }
사용하는 쪽에서 `println()`그대로 써서 사용하는게 이 코드를 처음 보는 개발자가 좀 더 이해하는게 빠를 것 같습니다!

2024-01-04 13:15 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +    companion object {
질문! kotlin에서 class와 object의 차이가 무엇일까요?

2024-01-12 14:32 UTC, nuyhhyun commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +    companion object {
class는 객체를 인스턴스화해서 사용해야 할 때 선언하는 방식이고,
object는 인스턴스화할 필요 없이 한 번만 사용할 때 싱글톤으로 선언하는 방식이라는 것이 차이점인 것 같습니다!
추가로 companion object는 class 안에서 싱글톤으로 선언해 사용하기 위한 방식입니다!

2024-01-12 14:35 UTC, nuyhhyun commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +        }
정답 상수화입니다!

2024-01-12 14:36 UTC, nuyhhyun commented on src/main/kotlin/racingcar/model/Car.kt
> +    }
리팩토링하면서 시도 횟수인 tryCounts 값을 설정하는 걸 함수화하지 않고 바로 대입하는 방식으로 바꿨는데, 이것도 외부에서 값을 변경할 수 있는 경우일까요? 아니면 초기화로 볼 수 있나요?

2024-01-15 12:16 UTC, croffle-lover requested changes
고생 많으셨습니다!

제일 지금 급선무는 객체를 다시 설계하시는게 좋을듯 합니다.

이 미션에 주어진 각 요구사항들은 어떤 객체에게 할당되어야할 책임인지 다시 한 번 고려해보시면 좋을 것 같습니다!

열심히해주셔서 감사합니다! 리뷰요청 기다리겠습니다!

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/Car.kt
> +        }
아마 생성자로 들어가는 프로퍼티에 custom setter를 지정해주지 못하여 `updatePosition`을 두신거 같은데, 

`position`을 생성자 밖에서 선언해주고 private set을 적용시키면 외부에서는 조작하지 못하는 가변적인 프로퍼티가 만들어 질거에요.

하지만 외부에서 조작을 못하면 협력하기 어려운 객체이니 함수로 한칸씩 만 움직일 것을 요청하게끔 하라는게 의도였습니다.

밑에 `handleUpdatePosition`을 public으로 풀면 될것 같네요.

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/Race.kt
> +) {
`data class`는 `class`와 어떤 차이가 있을까요?

이 Race라는 객체는 `class`여야 할까요 `object`여야 할까요?

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +    private val outputView = OutputView()
`OuputView`는 여러 개의 인스턴스가 필요한 객체일까요?

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +            car.updatePosition = rand
객체지향 생활체조 원칙 5. 줄여쓰지 않는다!

왜 줄여쓰면 안될까요? 

[참고](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93)

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/Validation.kt
> +    companion object {
현재 **입력과 관련된** 검증을 하는 클래스로 보이는데요.

이 클래스가 가진 검증 책임은 각각의 클래스에서 관리되는게 맞습니다.

예를 들어서, 자동차가 두 대 이상 있어야 한다는 것은 `Car`를 여러대 가져야 할 [일급컬렉션](https://jojoldu.tistory.com/412)에서 검증해야 하고요
자동차의 이름이 5자를 초과할 수 없다는 요구사항은 `Car` 객체에서 검증해야할 사항입니다.

각각의 모델에 맞는 요구사항들을 지키냐 안지키냐 검증을 할 책임은 각각의 올바른 모델에게 할당해주세요!

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/Validation.kt
> +    companion object {
현재 이 처럼 모델에 있어야 할 로직들이 여러군데로 펼쳐있으면 테스트하기도 불편할겁니다!

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/Validation.kt
> +    companion object {
모델에 대한 단위 테스트를 해야한다는 요구사항을 계속해서 지키지 못하시고 계시는데, 앞서 말한 문제점이 해결되면 하실 수 있을 겁니다!

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +class GameManager {
싱글톤이어도 상관없을 것 같습니다!

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +data class Car(val name: String, var position: Int)
요구사항들에 비해 `Car` 객체가 너무 간단합니다!

`Car` 객체에는 어떤 책임들이 있어야할까요?

2024-01-15 12:16 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +    }
`carList` 처럼 어떤 이름에 접미사로 자료구조의 이름을 사용하는 것은 지양해야 합니다.

만약에 자료구조를 set으로 바꾸게 된다면 그에 맞게 변수명 또한 변경되어야하는 번거로움이 있습니다.

`car`를 여럿을 가진 일급컬렉션을 만들어 관리하는 것은 어떨까요?
요구사항들을 보면 해당 일급컬렉션에서도 들어갈 여러가지 도메인 로직이 있을 것 같습니다!

2024-01-26 14:29 UTC, nuyhhyun commented on src/main/kotlin/racingcar/model/Race.kt
> +) {
`data class`가 data를 다루는 데에 적합하다는 것에만 홀려서 제대로 이해를 못하고 있었네요ㅠ

`data class`는 `class`와는 다르게 toString(), hashCode(), equals(), copy(), componentN functions 메소드를 자동으로 만들어준다고 합니다.

최소한의 변경으로 여러곳에서 재사용되며, 반복적으로 비슷한 형태를 띄는 코드인 보일러플레이트 코드를 줄일 수 있는 장점이 있다는데,
데이터만을 담는 class이면서 위에 명시된 함수들을 따로 선언하지 않고서도 사용이 용이하다는 것이 이에 해당하는 것 같습니다.

해당 메소드들은 아래 예시들과 같이 사용될 수 있습니다.
```kotlin
fun main() {
    val jun = Person("준", 24)

    // toString() - 결과 : Person(name=준, age=24)
    println(jun.toString())
    
    // hashCode() - 결과 : 1595160
    println(jun.hashCode())
    
    // equals() - 결과 : true
    val jun1 = Person("준", 24)
    println(jun.equals(jun1))    
    
    // equals() - 결과 : false
    val jun2 = Person("짭준", 25)
    println(jun.equals(jun2))

    // Destructuring Declaration 구문을 통해 객체를 여러 변수로 구조화
    val (name, age) = jun
    println(name) // 결과 - 준
    println(age) // 결과 - 24
}

data class Person(var name: String, val age: Int)
```
출처: https://velog.io/@jonmad/Til.-kotlin-Data-class%EC%99%80-%EB%B3%B4%EC%9D%BC%EB%9F%AC-%ED%94%8C%EB%A0%88%EC%9D%B4%ED%8A%B8 [Devback:velog]
<br/>

또한, 아래 예시처럼 `data class`는 우리가 직접 다루려 하는 data값을 표시하고, `class`는 그 주소값을 표시하여, data 자체를 다루기에는 `data class`가 훨씬 용이하다고 합니다.

```kotlin
data class User(var name:String = "", var age:Int = 0 )
class Use(var name:String, var age:Int)

fun main(args: Array) {     var exam = User()
    var exam1 = User("후니쓰")
    var exam2 = User(age = 22)
    var exam3 = User("후니쓰", 22)
    var test = Use("후니쓰", 24)
    
    println("User 사용 "+exam3)
    println("Use 사용 "+test)
}
```
![use User](https://github.com/croffle-lover/kotlin-racingcar/assets/52152418/36d64518-5173-46f5-90e7-605e33cd5d74)
출처: https://hoony-gunputer.tistory.com/entry/kotlinData-Class [후니의  컴퓨터:티스토리]
<br/>
class 안의 데이터들을 가공하거나 비교해야 할 때 `data class`를 사용하는 것 같아, 자동차 경주 게임 내에서 Car와 Race 객체는 `data class`의 이점이 굳이 필요하다고 보이지는 않습니다.

Car는 `class`로 변경하는 것이 맞을 것 같고,
Race의 경우에는 여러 자동차들을 한 번에 다루는 객체라 싱글톤으로 `object`로 변경하는 것이 맞을 것 같습니다!

2024-01-26 14:56 UTC, nuyhhyun commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +    private val outputView = OutputView()
출력만을 담당하는 객체라서 굳이 필요하지 않을 것 같아 싱글톤으로 바꾸는 게 더 적절할 것 같습니다!
OutputView도 object로 바꾸는 게 나을 것 같습니다!

2024-01-27 03:58 UTC, nuyhhyun commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +class GameManager {
Car은 여러 차가 만들어지니 `class`여야 할 거라고 생각했는데 `object`여도 되는군요..!! 인스턴스에 대한 이해가 잘못돼 있었던 것 같습니다 좀 더 공부하고 고민해보겠습니다!

2024-01-27 16:28 UTC, nuyhhyun commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +            car.updatePosition = rand
첫번째로, 그 의미를 정확히 알 수 없게 해서입니다. 개인 기준으로 축약을 하게 되면 그게 어떤 것을 담당하고 있는지 쉽게 알 수 없고, 이는 협업에서의 문제점으로도 이어질 수 있습니다!
두번째로, 줄여쓸만큼 이름이 길어질만 하다면, 그만큼 많은 책임이 한 번에 부여되어 있는 것이라고 합니다. 이름이 축약해야 할 정도로 길어질 필요성이 있다면 메소드를 분리하는 등의 책임 분배가 필요한 시점일 수 있다고 합니다.

첫번째는 신경쓰지 못했는데 두번째는 이번에 처음 알았네요!! 앞으로도 두 가지 유의해서 코딩해보겠습니다!!

2024-02-05 07:27 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +class GameManager {
아 제가 오해를 살만하게 리뷰를 적어뒀군요. ㅠㅠ
`GameManager`가 class일 필요가 없을것 같단 말이었습니다.

2024-02-05 07:29 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/Race.kt
> +) {
이 레이싱 게임은 자동차가 앞으로 간 거리를 통하여 우승자를 가려내고있습니다.
따라서
> class 안의 데이터들을 가공하거나 비교해야 할 때

이 말에 적합하단 느낌이 들죠?

car는 `data class`가 어울려 보입니다!

2024-02-05 08:24 UTC, croffle-lover requested changes
점점 나아지는 모습이 보입니다!
조금 더 힘냅시다!!

천천히 피드백 적용해보시고, 혼자 끙끙대지 마시고 언제든 질문 주세요!

열심히 하시는 모습 보기 좋습니다!

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +object GameManager {
적절한 싱글톤 사용 좋습니다 😄

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +    }
흠~ 상수화 할 수 있는 친구가 보이네요!

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/controller/GameManager.kt
> +            tryCounts = TryCounts.rightTryCountsInputValidation(tryCountsInput)
`rightTryCountsInputValidation()`

right 라는 접두사는 안붙어도 될 것 같습니다!

또한 메서드의 경우 동사여야하기 때문에

검증을 목적으로 한 메서드라면, `validateCarName` 이런 형식은 어떤가요?

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +        }
불필요한 주석이 포함되어있네요!

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/utils/Messages.kt
> +}
앞서 리뷰했듯 메시지들이 사용되는 위치에 각각 위치하는게 맞을 것 같습니다.

만약 지금처럼 프로젝트가 커져 메시지가 더 많아진다면 관리하기가 더 힘들어 질 것입니다!

또한 class에 companion object만 남겨서 구현할 거라면, 아에 object 또는 최상위에 정의하는게 맞아보입니다!

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/utils/Validations.kt
> +class Validations {
이것도 마찬가지로 있어야할 곳에 있는게 나을 것 같습니다!

만약 자동차의 이름을 검증하는거라면 자동차에 검증 로직이 존재하는게 응집도 있는 객체가 될 것 같습니다.

2024-02-05 08:24 UTC, croffle-lover commented on src/test/kotlin/modelTest/CarTest.kt
> +    }
`@CsvSource` 활용 좋습니다! 😄

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/Car.kt
> +    fun handleMovePosition(value: Int) {
그냥 `move()` 어떠신가요?

`car.move()`가 더 가독성이 좋을 것 같습니다!

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/Race.kt
> +    }
상태(cars)를 가지고 있을거면 class가 더 관리하기 쉬울것입니다.

지금의 경우 레이싱을 2경기를 동시에 진행한다 치면 `cars`가 아주 복잡해질 것입니다!!

class로 구현하고 생성자를 통해 주입받는 방식이 어떨까요?

추가로, 변수와 함수가 딱 붙어있는데 줄바꿈으로 구분해주는게 좋을 것 같습니다!

2024-02-05 08:24 UTC, croffle-lover commented on src/test/kotlin/modelTest/RandomNumberTest.kt
> +    }
안타깝지만, 랜덤으로 만들어지는 수를 테스트하는 것은 의미가 없습니다.

운이 좋아서 사실 0 ~ 11 까지 만들어지는걸 테스트에선 9까지만 만들어져서 테스트가 통과 되어 버릴 수 있기 때문이죠.

해당 테스트는 테스트의 목적인 검증의 의미를 벗어납니다!

2024-02-05 08:24 UTC, croffle-lover commented on src/test/kotlin/ui/InputViewTest.kt
> +    }
여기 테스트들도 한글로 다 바꿔주세요!

2024-02-05 08:24 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/RandomNumber.kt
> +}
`NumberGenerator`라는 interface를 두고

`RandomNumber`가 구현하도록 해보아요 일단!

이걸 사용하는 쪽(예: 함수)에서 타입을 interface인 `NumberGenerator`로 지정하면

이 인터페이스를 구현하는 모든 객체를 사용할 수 있습니다.

피자집에서 배달대행을 요청할 때 어떤 배달 대행사 한테 요청하던 배달만 잘 시켜주면 상관 없다 했죠?

지금 그걸 여기다 적용시키는 겁니다!

```kotlin
interface NumberGenerator {
    fun generateNumber(): Int
}
```

```kotlin
object RandomNumber: NumberGenerator {
    override fun generateNumber(): Int {
        return Random.nextInt(RANDOM_RANGE)
    }
}
```

2024-02-15 06:17 UTC, nuyhhyun commented on src/main/kotlin/racingcar/domain/GameManager.kt
> +        }
이전에 삭제한 코드가 반영이 안되어있었네요!! 삭제하면 안올라가는 줄 알았는데 삭제한 내용도 커밋을 해야 했군요ㅠㅠ 괜히 번거롭게 해드렸네요ㅠ 요거 포함해서 삭제 여부가 반영 안됐던 것들은 우주선 이모지 달아두었습니다!

2024-02-15 09:14 UTC, nuyhhyun commented on src/main/kotlin/racingcar/model/RandomNumber.kt
> +}
SAM에 대해서는 더 많은 공부가 필요하겠네요... 강의해주실 때는 이해되는 것 같았는데 직접 활용해보려 하니깐 어렵군요...

2024-03-03 11:58 UTC, croffle-lover requested changes
현님! 고생많으십니다!
처음과 비교해보면 엄청난 발전을 하고있어요!
아직 SAM이 어려우신듯 한데, 겁먹을 필요 없으십니다!
아직 람다가 어색하고, 새로운 개념들이니 충분히 그럴 수 있어요!
저도 처음엔 많이 어려워 하고 헷갈려 했던 기억이 있네요!! 

피드백 사항 몇가지 남겨드렸으니 수정하시구 다시 요청 주세요!

2024-03-03 11:58 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/RandomNumber.kt
> +}
```suggestion
fun interface NumberGenerator {
    fun generateNumber(): Int
}
```

이렇게 interface 앞에 fun을 붙이면 SAM으로 구현이 가능해집니다!

2024-03-03 11:58 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/RandomNumber.kt
> +    }
`RandomNumber`보단 좀 더 뭐하는 객체인지 아려면 어떻게 이름을 지어주는게 좋을까요?

2024-03-03 11:58 UTC, croffle-lover commented on src/main/kotlin/racingcar/model/TryCounts.kt
> +}
시도 회수가 0보다 커야하기 때문에 그 책임을 수행할 `TryCounts`를 만드셨네요!
좋습니다.
하지만 `tryCount`는 상태를 가지고 있습니다.
object가 상태를 가지고 있으면 어떤 일이 일어날까요?
object는 싱글톤 객체이므로, 어디서든 같은 객체로 접근이 가능하고 수정이 가능합니다.
지금 `var tryCounts`를 pivate set을 해놓으셨지만 여전히 함수로 public한 수정이 가능하구요.
이렇게 되면 프로그램이 더 예측하기가 힘든 방향이 되어버립니다.
여러 군데에서 수정이 가능하기 때문이죠!

class로 바꿔보는건 어떨까요? 그렇게 한다면, 지금 상황에서 set함수도 필요 없을 것 같습니다.!

2024-03-03 11:58 UTC, croffle-lover commented on src/main/kotlin/racingcar/view/OutputView.kt
> +        println(FINAL_WINNER + winnerNames)
우리 이 함수를 써서 리팩토링 해볼까요? 불필요한 반복문을 지울수 있을 것 같습니다!
[joinToString()](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/join-to-string.html)

2024-03-03 11:58 UTC, croffle-lover commented on src/test/kotlin/modelTest/RaceTest.kt
> +    }
`val raceValidation` 은 어떤 타입일까요?  현재 이 테스트 코드만을 봐서는 모르겠습니다!

참고 : Effective Kotlin - 아이템 14 변수타입이 명확하지 않은 경우 확실하게 지정하라

2024-03-03 11:58 UTC, croffle-lover commented on src/test/kotlin/modelTest/RaceTest.kt
> +    }
코드에는 문맥이란게 존재합니다.

예를들어 친구에게 어떤 이야기를 들려줄때 '걔가 그걸 샀어' 이러한 표현을 많이 쓰는거 보다, '민수가 아이폰을 샀어'라고 표현하는게 더 이해하기 쉽겠죠?

마찬가지입니다. 자기 코드를 남이 처음 본다 생각하고 그 처음 보는 사람의 관점에서 고민하고 배려를 해야 비로소 읽기 좋은 코드가 됩니다!

항상 마음에 담아두시고 코딩하시면 좋을 것 같습니다!
저도 가끔씩 놓치는 사항이에요! ㅋㅋㅋ 같이 화이팅!

2024-03-03 11:58 UTC, croffle-lover commented on src/test/kotlin/modelTest/TryCountsTest.kt
> +    }
시도 회수를 잘못 입력했다면 0이 아닌 예외로 처리하는게 어떨까요?

2024-03-03 11:58 UTC, croffle-lover commented on src/test/kotlin/modelTest/RaceTest.kt
> +    }
`race.playOneRound(RandomNumber)`

`NumberGenerator`를 `fun interface`로 만드셨다면 다음 처럼 수정이 가능하고,
이는 랜덤값으로 테스트하기 힘든 것을 분리하여 테스트를 가능하게 합니다.

`race.playOneRound { 4 }`

이렇게 하면 숫자가 고정으로 4가 나오니 전진 한다는걸 테스트 해볼 수가 있습니다!

2024-03-04 14:22 UTC, croffle-lover approved these changes
너무 고생하셨습니다 현님! 자동차 미션 어떠셨나요? 
항상 성장하고 어제보다 나은 개발자가 되기를 바라겠습니다!

2024-03-04 14:22 UTC, merged